name: 'Linter'
on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-app:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
